version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "*"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "DEP"
    open-pull-requests-limit: 10
